#!/usr/bin/env python3
import logging
logger = logging.getLogger(__name__)

# Langue par défaut
DEFAULT_LANG = "en"

# Dictionnaire des traductions
TRANSLATIONS = {
    "en": {
        "app_title": "Elite: Dangerous Mission Optimizer 3.0 by Commander SnakeDrake",
        "location_label_prefix": "Location:",
        "ship_label_prefix": "Ship:",
        "cargo_label_prefix": "Cargo:",
        "db_status_label_prefix": "Local DB:",
        "status_ready": "Ready. Refresh location/ship or launch analysis.",
        "refresh_button": "🔄 Refresh Loc/Ship",
        "update_db_button": "Update DB",
        "launch_analysis_button": "🚀 Launch Analysis",
        "settings_button": "⚙️ Settings",
        "cancel_button": "Cancel",
        "commod_suggestions_button": "📊 Commodities Suggestions",
        "journal_dir_custom_prefix": "Journal (Custom):",
        "journal_dir_auto_prefix": "Journal (Auto):",
        "journal_dir_not_found": "Journal: Not Found (Auto-detect failed)",
        "journal_dir_auto_detecting": "Journal: Auto-detecting...",
        "location_ship_refreshed": "Location and Ship refreshed.",
        "error_refresh_thread": "Error in refresh thread: {error}",
        "pad_size_unknown_status": "Ship '{ship_type}' detected, pad size unknown. Enter it below.",
        "pad_for_ship_label": "Pad for '{ship_type}':",
        "save_pad_button": "Save Pad",
        "status_saving_pad_size": "Saving pad size...",
        "error_current_ship_unknown_pad": "Error: Current ship type unknown, cannot save pad size.",
        "pad_size_error": "Pad Size Error: {error}",
        "pad_size_saved_status": "Pad size ({pad_size}) for '{ship_type}' saved.",
        "failed_to_save_settings_after_pad": "Failed to save settings (after pad size update).",
        "cancellation_requested": "Cancellation requested...",
        "error_db_update_no_system": "Cannot update DB: Current system unknown/invalid. Refresh location/ship.",
        "status_validating_settings_db_update": "Validating settings for DB Update...",
        "status_updating_databases_for_system": "Updating databases for {system}...",
        "status_db_update_finished": "DB Update finished.",
        "status_db_update_departure_error": " (Departure data error)",
        "status_db_update_local_error": " (Local data error)",
        "status_db_update_cancelled": "DB Update Cancelled.",
        "status_db_update_error_generic": "DB Update Error: {error}",
        "status_db_update_thread_error": "Unexpected DB Update Thread Error: {error}",
        "settings_error_db_update": "Settings Error for DB Update: {error}",
        "analysis_tab_title": "Analysis & Trade",
        "services_tab_title": "Nearest Station Services",
        "error_launch_analysis_no_system": "Cannot launch: Current system/ship unknown. Refresh location/ship.",
        "error_launch_analysis_no_journal": "Cannot launch: Journal directory not set/found or invalid. Check settings or refresh.",
        "status_starting_analysis": "Starting analysis...",
        "status_validating_settings_analysis": "Validating settings for analysis...",
        "settings_error_analysis": "Settings Error for Analysis: {error}",
        "launch_error_analysis": "Launch Error: {error}",
        "async_analysis_error": "Async analysis error: {error}\nConsult logs.",
        "status_loading_journal": "Loading journal events...",
        "status_parsing_missions": "Parsing active missions...",
        "status_checking_market_data": "Checking/Updating market data...",
        "status_db_update_progress_prefix": "DB Update",
        "status_analyzing_purchase_options": "Analyzing mission purchase options...",
        "status_finalizing_analysis": "Finalizing analysis...",
        "status_analysis_finished": "Analysis finished.",
        "status_analysis_error_generic": "Analysis finished with errors.",
        "status_analysis_cancelled": "Analysis cancelled.",
        "analysis_cancelled_by_user_message": "Analysis cancelled by user.",
        "critical_error_analysis_task": "A critical error occurred during analysis:\n{error}\n\nConsult {log_file} for more details.",
        "analysis_complete_no_suggestions": "Analysis complete. No specific suggestions or needs found.",
        "no_mission_data_display": "No mission data to display based on current criteria.",
        "no_trade_data_display": "No trade data to display based on current criteria.",
        "no_active_missions_found": "No active missions found.",
        "settings_window_title": "Settings - Mission Optimizer",
        "settings_journal_dir_label": "Journal Directory",
        "settings_change_journal_dir_button": "Change Journal Directory",
        "settings_search_params_label": "Search Parameters",
        "settings_radius_label": "Radius (LY):",
        "settings_db_age_label": "DB Age (days):",
        "settings_max_station_dist_label": "Max Station Dist (LS):",
        "settings_include_planetary_cb": "Include Planetary Stations",
        "settings_include_fc_cb": "Include Fleet Carriers",
        "settings_actions_label": "Actions",
        "settings_save_button": "💾 Save Settings",
        "settings_restore_defaults_button": "Restore Defaults",
        "settings_close_button": "Close",
        "settings_language_label": "Language:",
        "settings_status_saving": "Saving...",
        "settings_status_restoring": "Restoring defaults...",
        "settings_saved_successfully": "Settings saved successfully.",
        "settings_failed_to_save": "Failed to save settings. Check logs.",
        "settings_validation_error": "Settings Validation Error: {error}",
        "settings_error_saving": "Error saving settings: {error}",
        "message_box_restore_defaults_title": "Restore Defaults",
        "message_box_restore_defaults_content": "Are you sure you want to restore all settings to their default values?\nThis includes journal directory, search parameters, sort option and custom ship pad sizes.\nOther analysis parameters (like num journal files read) will also be reset.\nThe application will save these defaults immediately.",
        "settings_defaults_restored_saved": "Default settings restored and saved.",
        "settings_failed_save_restored": "Failed to save restored default settings.",
        "commod_sugg_window_title": "Commodity Purchase Suggestions (from Local Data)",
        "commod_sugg_status_loading": "Loading data from local cache...",
        "commod_sugg_error_loading_local": "Error loading local data: {error}",
        "commod_sugg_local_data_not_found": "{file_name} not found. Run analysis to generate it.",
        "commod_sugg_error_dialog_title": "Error", # Already exists, can be reused
        "commod_sugg_data_missing_dialog_title": "Data Missing",
        "commod_sugg_items_found": "{count} items found.",
        "commod_sugg_no_export_data": "No export data for this station in local cache or station doesn't sell.",
        "commod_sugg_loaded": "Commodity suggestions loaded from local data.",
        "tree_col_commodity_name": "Commodity Name",
        "tree_col_price_player_buys": "Price (Player Buys)",
        "tree_col_stock": "Stock",
        "error_service_search_no_system": "Current system is unknown. Please refresh location.",
        "error_service_search_no_service": "Please select a service type.",
        "status_service_searching_for": "Searching for '{service}'...",
        "status_service_search_cancelled": "Search cancelled.",
        "status_service_api_error": "API Error: {error_message}",
        "status_service_no_stations_found": "No stations found or unexpected API response.",
        "status_service_found_stations": "Found {count} stations.",
        "status_service_error_fetching": "Error: {error}",
        "service_select_and_find": "Select service and click find.",
        "service_type_label": "Service Type:",
        "service_min_pad_label": "Min Pad:",
        "service_find_button": "Find Nearest Services",
        "service_pad_any": "Any",
        "service_pad_small": "S (Small)",
        "service_pad_medium": "M (Medium)",
        "service_pad_large": "L (Large)",
        "tree_col_station": "Station",
        "tree_col_system": "System",
        "tree_col_distance_ly": "Distance (LY)",
        "tree_col_pad": "Pad",
        "tree_col_dist_star_ls": "Dist. Star (LS)",
        "tree_col_faction": "Faction",
        "sort_by_dist_ly": "Dist. LY",
        "sort_by_profit": "Profit",
        "sort_by_dist_ls": "Dist. LS",
        "missions_needs_label": "NEEDS: {count} type(s) ({total_units} units). Est. Reward:",
        "missions_ship_label": "SHIP: {ship_type} (Pad {pad_size}), Cargo: {cargo_capacity} t.",
        "missions_est_trips_label": "Est. trips: {trips}",
        "missions_filters_label": "FILTERS: Station dist. max {dist_ls:.0f} LS. Planetary: {planetary}. Fleet Carriers: {fc}.",
        "missions_sorting_label": "SORTING (Full Supply): By {sort_option}.",
        "missions_supply_options_header": "MISSION COMMODITY SUPPLY OPTIONS",
        "missions_full_supply_options_subheader": "FULL Supply Options (Top 5 shown):",
        "missions_partial_supply_options_subheader": "PARTIAL Supply Options (Top shown, sorted by most items covered):",
        "missions_no_full_supply": "No single station found for FULL supply.",
        "missions_no_supply_options": "No supply options found matching criteria.",
        "missions_round_trip_header": "ROUND TRIP TRADE OPPORTUNITIES (Mission Related)",
        "missions_no_stations_for_round_trip": "No mission supply stations identified to check for round trip trades.",
        "missions_trade_ops_for_trip_to": "--- Trade Ops for trip to: {station_name} ({system_name}) ---",
        "missions_outbound_from_to": "Outbound (from {current_station} to {pickup_station}):",
        "missions_return_leg_from_to": "Return Leg (from {pickup_station} to {current_station}, {cargo_space}t spare capacity):",
        "missions_no_profitable_outbound": "(No profitable outbound trades found for available cargo)",
        "missions_no_profitable_return": "(No profitable return trades found or no spare cargo)",
        "general_market_trade_routes_header": "GENERAL MARKET TRADE ROUTES (Top {count})",
        "general_no_routes_found": "No profitable general trade routes found in the vicinity matching criteria.",
        "general_route_display": "Route {index}: {route_type}",
        "general_route_dest_details": "(Dest: {ly_dist}{separator}{ls_dist})",
        "general_route_source_details": "(Source: {ly_dist}{separator}{ls_dist})",
        "general_suggested_outbound_to": "Suggested Outbound to {station_name}{details}:",
        "general_main_leg_buy": "Main Leg: Buy {commodity} (Qty: {quantity})",
        "general_from_station_details": "From: {station_details} @",
        "general_sell_to_station_details": "Sell To: {station_details} @",
        "general_profit_per_unit": "Profit/unit:",
        "general_total_profit_qty": "Total Profit for Qty:",
        "buy_at_price": "{price:,.0f} CR/u",
        "sell_at_price": "{price:,.0f} CR/u",
        "total_profit_value": "{profit:,.0f} CR",
        "planetary_filter_included": "Included",
        "planetary_filter_excluded": "Excluded",
        "fc_filter_included": "Included",
        "fc_filter_excluded": "Excluded",
        "journal_dir_set_permanent_status": "Journal Dir set. Save settings to make permanent.",
        "to_collect_label": "To Collect:",
        "total_units_label": "Total: {total_units} u ({num_types} types)",
        "no_active_missions_label": "No active missions or needs.",
        "total_zero_label": "Total: 0 u (0 types)",
        "commod_sugg_no_sourcing_stations_info": "No sourcing stations identified. Run analysis with active missions first.",
        "status_label_sort_full_by": "Sort Full by:",
        "error_dialog_title": "Error", # Already exists
        "warning_title": "Warning", # New general key
        "status_refreshing_location_ship": "Refreshing location/ship...",
        "status_validating_saving_settings": "Validating and saving settings...",
        "shipyard_tab_title": "Shipyard",
        "error_shipyard_find_ship_generic": "Error finding ship: {error}",
        "shipyard_radius_label": "Shipyard Radius (LY)",
        "shipyard_select_ship_label": "Ship",
        "shipyard_find_ship_button": "Find Ship",
        "shipyard_update_db_button": "Update DB Shipyard",
        "tree_col_shipyard_station": "Station",
        "tree_col_shipyard_system": "System",
        "tree_col_shipyard_dist_ly": "Distance LY",
        "tree_col_shipyard_dist_ls": "Distance LS",
        "tree_col_shipyard_type": "Station Type",
        "shipyard_select_ship_and_find": "Select a Ship and find it",
        "status_shipyard_found_stations": "Results",
        "status_shipyard_db_update_finished": "Update DB finished",
        "settings_shipyard_radius_label": "Radius Shipyard (LY)",
        "tree_col_shipyard_pad_size": "Pad",
        "outfitting_tab_title": "Outfitting",
        "outfitting_category_label": "Category:",
        "outfitting_module_label": "Module:",
        "outfitting_search_button": "Search Outfitting",
        "outfitting_tab_search_title": "Outfitting research",
        "outfitting_tab_results_title": "Outfitting results",
        "outfitting_radius_label": "Outfitting Radius (LY)",
        "outfitting_update_db_button": "Update DB Outfitting",
        "outfitting_add_to_list_btn": "Add module to list",
        "outfitting_search_list_label": "Outfitting module search list",
        "outfitting_remove_from_list_btn": "Remove module from list",
        "outfitting_search_initial_status": "Waiting for search",
        "tree_col_outfitting_station": "Station Name",
        "tree_col_outfitting_system": "System Name",
        "tree_col_outfitting_dist_ly": "Distance LY",
        "tree_col_outfitting_pad_size": "Pad Size",
        "tree_col_outfitting_dist_ls": "Distance LS",
        "tree_col_outfitting_type": "Station Type",
        "tree_col_outfitting_modules_matched_ui": "Modules Matched",
        "status_outfitting_found_stations_multimodule": "Results",
        "status_outfitting_no_stations_found_multimodule": "No results, try to change your search",
        "outfitting_size_filter_label": "Module Size",
        "outfitting_class_filter_label": "Module Class",
        "filter_any": "All",
        "outfitting_mount_filter_label": "Mount Type",
        "mount_fixed": "Fixed",
        "mount_turreted": "Turreted",
        "mount_gimballed": "Gimballed",
        "outfitting_results_initial_status": "Results initial status",

        # --- Materials Tab ---
        "materials_tab_title": "Engineering Materials",
        "refresh_materials_button": "🔄 Refresh Materials",
        "material_category_raw": "Raw",
        "material_category_manufactured": "Manufactured",
        "material_category_encoded": "Encoded",
        "material_name_header": "Material",
        "material_grade_header": "Grade",
        "material_quantity_header": "Qty",
        "material_limit_header": "Limit",
        "material_percentage_header": "% Full",
        "materials_status_idle": "Materials: Ready. Press refresh to load inventory.",
        "materials_status_not_loaded": "Materials: Data not loaded.",
        "materials_status_updated_at": "Materials last updated: {timestamp}",
        "materials_status_loading": "Materials: Loading inventory from journal...",
        "materials_status_load_failed": "Materials: Failed to load inventory.",
        "materials_journal_dir_not_found_error": "Cannot load materials: Journal directory not found. Check settings.",
        "materials_no_journal_events_status": "Materials: No journal events found. Try logging into the game.",
        "materials_event_not_found_warning": "Could not find recent 'Materials' event in journal. Ensure you've logged into the game recently.",
        "materials_error_refreshing": "Error refreshing materials data: {error}",
        "materials_updated_at": "Materials updated at",
        
        # ... (vos clés anglaises existantes) ...
        "multihop_trade_tab_title": "Multi-Hop Trade Planner", # Déjà ajouté

        # --- Multi-Hop Trade Tab UI ---
        "multihop_config_frame_title": "Route Configuration",
        "multihop_num_hops_label": "Number of Hops (1-10):",
        "multihop_max_ly_per_hop_label": "Max LY per Hop:",
        "multihop_start_planning_button": "▶️ Start Route Planning",
        "multihop_restart_planning_button": "🔄 Restart Planning",

        "multihop_current_hop_frame_title": "Current Hop Planning",
        "multihop_hop_details_label": "Hop {current_hop_num}/{total_hops_num}: From {current_station_name} ({current_system_name})",
        "multihop_suggestions_label": "Top 5 Trade Options for this Hop:",
        "multihop_select_and_continue_button": "Select & Plan Next Hop ({remaining_hops} left)",
        "multihop_select_and_finish_button": "Select & Finish Route", # Pour le dernier saut

        "multihop_summary_frame_title": "Planned Route Summary",
        "multihop_clear_summary_button": "Clear Summary",

        # Treeview Column Headers for Multi-Hop
        "multihop_col_dest_station": "Destination Station",
        "multihop_col_dest_system": "System",
        "multihop_col_commodity_to_buy": "Buy Commodity",
        "multihop_col_profit_per_unit": "Profit/Unit",
        "multihop_col_est_total_profit": "Est. Total Profit", # For full cargo
        "multihop_col_distance_ly": "Dist. (LY)",
        "multihop_col_landing_pad": "Pad",
        "multihop_col_dist_to_star": "Dist. Star (LS)",
        "multihop_col_buy_price_at_source": "Buy Price (Source)",
        "multihop_col_sell_price_at_dest": "Sell Price (Dest)",

        # Status/Error Messages for Multi-Hop
        "multihop_status_idle": "Configure route and start planning.",
        "multihop_status_input_hops_num_error": "Number of hops must be between 1 and 10.",
        "multihop_status_input_max_ly_error": "Max LY per hop must be a positive number.",
        "multihop_status_player_info_error": "Error: Could not get current player location/ship. Please refresh in Analysis tab.",
        "multihop_status_validating_inputs": "Multi-Hop: Validating inputs...",
        "multihop_status_getting_player_info": "Multi-Hop: Fetching initial player data...",
        "multihop_status_starting_planning": "Starting multi-hop planning...",
        "multihop_status_planning_hop": "Planning hop {hop_num_current} of {hop_num_total} from {station_name}...",
        "multihop_status_updating_market_data": "Updating market data for {system_name} vicinity...",
        "multihop_status_finding_trades": "Finding best trades from {station_name}...",
        "multihop_status_no_trades_found": "No profitable trades found for this hop matching criteria.",
        "multihop_status_select_next_hop": "Please select a trade for the next hop from the list above.",
        "multihop_status_route_complete": "Multi-hop route planning complete. See summary below.",
        "multihop_status_route_cancelled": "Multi-hop route planning cancelled.",
        "multihop_summary_leg": "Leg {leg_num}: From {source_station} ({source_system}) to {dest_station} ({dest_system})", # Ancienne version (peut être gardée ou supprimée)
        "multihop_summary_leg_with_distances": "Leg {leg_num}: From {source_station} ({source_system}) to {dest_station} ({dest_system}) [{dist_ly} LY, {dist_ls} LS]", # <<< NOUVELLE/MODIFIÉE
        "multihop_summary_buy": "  Buy: {quantity} x {commodity_name} @ {buy_price_each:,.0f} CR each.",
        "multihop_summary_sell": "  Sell: {commodity_name} @ {sell_price_each:,.0f} CR each.",
        "multihop_summary_profit_leg": "  Leg Profit: {leg_profit:,.0f} CR",
        "multihop_summary_total_profit": "Estimated Total Route Profit: {total_route_profit:,.0f} CR",
        
        # --- Multi-Hop Route Cache ---
        "multihop_status_loaded_saved_route": "Loaded previously saved route.",
        "multihop_status_no_saved_route": "No saved route found. Configure new route.",
        "multihop_status_route_saved": "Current route saved.",
        "multihop_status_cleared_saved_route": "Saved route cleared. Configure new route."
    },
    "fr": {
        "app_title": "Elite: Dangerous Mission Optimizer 3.0 par Commandant SnakeDrake",
        "location_label_prefix": "Lieu :",
        "ship_label_prefix": "Vaisseau :",
        "cargo_label_prefix": "Soute :",
        "db_status_label_prefix": "BD Locale :",
        "status_ready": "Prêt. Rafraîchir lieu/vaisseau ou lancer l'analyse.",
        "refresh_button": "🔄 Rafraîchir Lieu/Vaisseau",
        "update_db_button": "MàJ BD",
        "launch_analysis_button": "🚀 Lancer l'Analyse",
        "settings_button": "⚙️ Paramètres",
        "cancel_button": "Annuler",
        "commod_suggestions_button": "📊 Suggestions Marchandises",
        "journal_dir_custom_prefix": "Journal (Perso) :",
        "journal_dir_auto_prefix": "Journal (Auto) :",
        "journal_dir_not_found": "Journal : Non trouvé (auto-détection échouée)",
        "journal_dir_auto_detecting": "Journal : Auto-détection...",
        "location_ship_refreshed": "Lieu et Vaisseau rafraîchis.",
        "error_refresh_thread": "Erreur dans le thread de rafraîchissement : {error}",
        "pad_size_unknown_status": "Vaisseau '{ship_type}' détecté, taille d'aire inconnue. Entrez-la ci-dessous.",
        "pad_for_ship_label": "Aire pour '{ship_type}' :",
        "save_pad_button": "Sauver Aire",
        "status_saving_pad_size": "Sauvegarde de la taille de l'aire...",
        "error_current_ship_unknown_pad": "Erreur : Type de vaisseau actuel inconnu, impossible de sauver l'aire.",
        "pad_size_error": "Erreur Taille Aire : {error}",
        "pad_size_saved_status": "Taille d'aire ({pad_size}) pour '{ship_type}' sauvée.",
        "failed_to_save_settings_after_pad": "Échec de la sauvegarde des paramètres (après MàJ de l'aire).",
        "cancellation_requested": "Annulation demandée...",
        "error_db_update_no_system": "MàJ BD impossible : Système actuel inconnu/invalide. Rafraîchir lieu/vaisseau.",
        "status_validating_settings_db_update": "Validation des paramètres pour MàJ BD...",
        "status_updating_databases_for_system": "Mise à jour des bases de données pour {system}...",
        "status_db_update_finished": "MàJ BD terminée.",
        "status_db_update_departure_error": " (Erreur données départ)",
        "status_db_update_local_error": " (Erreur données locales)",
        "status_db_update_cancelled": "MàJ BD Annulée.",
        "status_db_update_error_generic": "Erreur MàJ BD : {error}",
        "status_db_update_thread_error": "Erreur inattendue Thread MàJ BD : {error}",
        "settings_error_db_update": "Erreur Paramètres pour MàJ BD : {error}",
        "analysis_tab_title": "Analyse & Commerce",
        "services_tab_title": "Services Station Proches",
        "error_launch_analysis_no_system": "Lancement impossible : Système/vaisseau actuel inconnu. Rafraîchir lieu/vaisseau.",
        "error_launch_analysis_no_journal": "Lancement impossible : Répertoire journal non défini/trouvé ou invalide. Vérifier paramètres ou rafraîchir.",
        "status_starting_analysis": "Démarrage de l'analyse...",
        "status_validating_settings_analysis": "Validation des paramètres pour analyse...",
        "settings_error_analysis": "Erreur Paramètres pour Analyse : {error}",
        "launch_error_analysis": "Erreur Lancement : {error}",
        "async_analysis_error": "Erreur analyse asynchrone : {error}\nConsultez les logs.",
        "status_loading_journal": "Chargement des événements du journal...",
        "status_parsing_missions": "Analyse des missions actives...",
        "status_checking_market_data": "Vérification/MàJ des données de marché...",
        "status_db_update_progress_prefix": "MàJ BD",
        "status_analyzing_purchase_options": "Analyse des options d'achat de mission...",
        "status_finalizing_analysis": "Finalisation de l'analyse...",
        "status_analysis_finished": "Analyse terminée.",
        "status_analysis_error_generic": "Analyse terminée avec erreurs.",
        "status_analysis_cancelled": "Analyse annulée.",
        "analysis_cancelled_by_user_message": "Analyse annulée par l'utilisateur.",
        "critical_error_analysis_task": "Une erreur critique est survenue pendant l'analyse :\n{error}\n\nConsultez {log_file} pour plus de détails.",
        "analysis_complete_no_suggestions": "Analyse complète. Aucune suggestion spécifique ou besoin trouvé.",
        "no_mission_data_display": "Aucune donnée de mission à afficher selon les critères actuels.",
        "no_trade_data_display": "Aucune donnée commerciale à afficher selon les critères actuels.",
        "no_active_missions_found": "Aucune mission active trouvée.",
        "settings_window_title": "Paramètres - Mission Optimizer",
        "settings_journal_dir_label": "Répertoire du Journal",
        "settings_change_journal_dir_button": "Changer Répertoire Journal",
        "settings_search_params_label": "Paramètres de Recherche",
        "settings_radius_label": "Rayon (AL) :",
        "settings_db_age_label": "Âge BD (jours) :",
        "settings_max_station_dist_label": "Dist. Max Station (SL) :",
        "settings_include_planetary_cb": "Inclure Stations Planétaires",
        "settings_include_fc_cb": "Inclure Fleet Carriers",
        "settings_actions_label": "Actions",
        "settings_save_button": "💾 Enregistrer Paramètres",
        "settings_restore_defaults_button": "Restaurer Défauts",
        "settings_close_button": "Fermer",
        "settings_language_label": "Langue :",
        "settings_status_saving": "Enregistrement...",
        "settings_status_restoring": "Restauration des défauts...",
        "settings_saved_successfully": "Paramètres enregistrés avec succès.",
        "settings_failed_to_save": "Échec de l'enregistrement des paramètres. Consultez les logs.",
        "settings_validation_error": "Erreur de Validation des Paramètres : {error}",
        "settings_error_saving": "Erreur d'enregistrement des paramètres : {error}",
        "message_box_restore_defaults_title": "Restaurer les paramètres par défaut",
        "message_box_restore_defaults_content": "Êtes-vous sûr de vouloir restaurer tous les paramètres à leurs valeurs par défaut ?\nCela inclut le répertoire du journal, les paramètres de recherche, l'option de tri et les tailles de soute personnalisées des vaisseaux.\nLes autres paramètres d'analyse (comme le nombre de fichiers journaux lus) seront également réinitialisés.\nL'application enregistrera ces paramètres par défaut immédiatement.",
        "settings_defaults_restored_saved": "Paramètres par défaut restaurés et enregistrés.",
        "settings_failed_save_restored": "Échec de la sauvegarde des paramètres par défaut restaurés.",
        "commod_sugg_window_title": "Suggestions d'Achat de Marchandises (Données Locales)",
        "commod_sugg_status_loading": "Chargement des données depuis le cache local...",
        "commod_sugg_error_loading_local": "Erreur de chargement des données locales : {error}",
        "commod_sugg_local_data_not_found": "{file_name} non trouvé. Lancez une analyse pour le générer.",
        "commod_sugg_error_dialog_title": "Erreur", # Déjà existant
        "commod_sugg_data_missing_dialog_title": "Données Manquantes",
        "commod_sugg_items_found": "{count} articles trouvés.",
        "commod_sugg_no_export_data": "Aucune donnée d'export pour cette station dans le cache local ou la station ne vend pas.",
        "commod_sugg_loaded": "Suggestions de marchandises chargées depuis les données locales.",
        "tree_col_commodity_name": "Nom Marchandise",
        "tree_col_price_player_buys": "Prix (Achat Joueur)",
        "tree_col_stock": "Stock",
        "error_service_search_no_system": "Système actuel inconnu. Veuillez rafraîchir la position.",
        "error_service_search_no_service": "Veuillez sélectionner un type de service.",
        "status_service_searching_for": "Recherche de '{service}'...",
        "status_service_search_cancelled": "Recherche annulée.",
        "status_service_api_error": "Erreur API : {error_message}",
        "status_service_no_stations_found": "Aucune station trouvée ou réponse API inattendue.",
        "status_service_found_stations": "{count} stations trouvées.",
        "status_service_error_fetching": "Erreur : {error}",
        "service_select_and_find": "Sélectionnez un service et cliquez sur trouver.",
        "service_type_label": "Type de Service :",
        "service_min_pad_label": "Aire Min :",
        "service_find_button": "Trouver Services Proches",
        "service_pad_any": "Toutes",
        "service_pad_small": "S (Petite)",
        "service_pad_medium": "M (Moyenne)",
        "service_pad_large": "L (Grande)",
        "tree_col_station": "Station",
        "tree_col_system": "Système",
        "tree_col_distance_ly": "Distance (AL)",
        "tree_col_pad": "Aire",
        "tree_col_dist_star_ls": "Dist. Étoile (SL)",
        "tree_col_faction": "Faction",
        "sort_by_dist_ly": "Dist. AL",
        "sort_by_profit": "Profit",
        "sort_by_dist_ls": "Dist. SL",
        "missions_needs_label": "BESOINS : {count} type(s) ({total_units} unités). Réc. Estimée :",
        "missions_ship_label": "VAISSEAU : {ship_type} (Aire {pad_size}), Soute : {cargo_capacity} t.",
        "missions_est_trips_label": "Voyages est. : {trips}",
        "missions_filters_label": "FILTRES : Dist. station max {dist_ls:.0f} SL. Planétaires : {planetary}. Fleet Carriers : {fc}.",
        "missions_sorting_label": "TRI (Appro. Complet) : Par {sort_option}.",
        "missions_supply_options_header": "OPTIONS D'APPROVISIONNEMENT MARCHANDISES MISSION",
        "missions_full_supply_options_subheader": "Options Appro. COMPLET (Top 5 affichées) :",
        "missions_partial_supply_options_subheader": "Options Appro. PARTIEL (Top affichées, triées par max. d'objets couverts) :",
        "missions_no_full_supply": "Aucune station unique trouvée pour l'approvisionnement COMPLET.",
        "missions_no_supply_options": "Aucune option d'approvisionnement trouvée correspondant aux critères.",
        "missions_round_trip_header": "OPPORTUNITÉS COMMERCIALES ALLER-RETOUR (Liées aux Missions)",
        "missions_no_stations_for_round_trip": "Aucune station d'appro. mission identifiée pour vérifier les A/R commerciaux.",
        "missions_trade_ops_for_trip_to": "--- Opérations Commerciales pour voyage vers : {station_name} ({system_name}) ---",
        "missions_outbound_from_to": "Aller (de {current_station} vers {pickup_station}) :",
        "missions_return_leg_from_to": "Retour (de {pickup_station} vers {current_station}, {cargo_space}t de soute dispo) :",
        "missions_no_profitable_outbound": "(Aucun commerce aller profitable trouvé pour la soute disponible)",
        "missions_no_profitable_return": "(Aucun commerce retour profitable trouvé ou pas de soute disponible)",
        "general_market_trade_routes_header": "ROUTES COMMERCIALES GÉNÉRALES (Top {count})",
        "general_no_routes_found": "Aucune route commerciale générale profitable trouvée aux alentours correspondant aux critères.",
        "general_route_display": "Route {index} : {route_type}",
        "general_route_dest_details": "(Dest : {ly_dist}{separator}{ls_dist})",
        "general_route_source_details": "(Source : {ly_dist}{separator}{ls_dist})",
        "general_suggested_outbound_to": "Aller suggéré vers {station_name}{details} :",
        "general_main_leg_buy": "Trajet Principal : Acheter {commodity} (Qté : {quantity})",
        "general_from_station_details": "De : {station_details} @",
        "general_sell_to_station_details": "Vendre À : {station_details} @",
        "general_profit_per_unit": "Profit/unité :",
        "general_total_profit_qty": "Profit Total pour Qté :",
        "buy_at_price": "{price:,.0f} CR/u",
        "sell_at_price": "{price:,.0f} CR/u",
        "total_profit_value": "{profit:,.0f} CR",
        "planetary_filter_included": "Incluses",
        "planetary_filter_excluded": "Exclues",
        "fc_filter_included": "Inclus",
        "fc_filter_excluded": "Exclus",
        "journal_dir_set_permanent_status": "Rép. Journal défini. Enregistrez les paramètres pour rendre permanent.",
        "to_collect_label": "À Collecter :",
        "total_units_label": "Total : {total_units} u ({num_types} types)",
        "no_active_missions_label": "Aucune mission active ou besoin.",
        "total_zero_label": "Total : 0 u (0 types)",
        "commod_sugg_no_sourcing_stations_info": "Aucune station source identifiée. Lancez une analyse avec des missions actives d'abord.",
        "status_label_sort_full_by": "Trier Complet par :",
        "error_dialog_title": "Erreur", # Déjà existant
        "warning_title": "Avertissement", # Nouvelle clé générale
        "status_refreshing_location_ship": "Rafraîchissement lieu/vaisseau...",
        "status_validating_saving_settings": "Validation et enregistrement des paramètres...",
        "shipyard_tab_title": "Chantier Naval",
        "error_shipyard_find_ship_generic": "Erreur lors de la recherche du vaisseau : {error}",
        "shipyard_radius_label": "Rayon (AL)",
        "shipyard_select_ship_label": "Vaisseau",
        "shipyard_find_ship_button": "Trouver Vaisseau",
        "shipyard_update_db_button": "Maj DB Chantier Naval",
        "tree_col_shipyard_station": "Station",
        "tree_col_shipyard_system": "Système",
        "tree_col_shipyard_dist_ly": "Distance AL",
        "tree_col_shipyard_dist_ls": "Distance SL",
        "tree_col_shipyard_type": "Type de Station",
        "shipyard_select_ship_and_find": "Choisis un Vaisseau et cherche le",
        "status_shipyard_found_stations": "Résultats",
        "status_shipyard_db_update_finished": "Maj DB terminée",
        "settings_shipyard_radius_label": "Rayon Chantier Naval (AL)",
        "tree_col_shipyard_pad_size": "Aire",
        "outfitting_tab_title": "Équipement",
        "outfitting_category_label": "Catégorie :",
        "outfitting_module_label": "Module :",
        "outfitting_search_button": "Rechercher Équipement",
        "outfitting_tab_search_title": "Recherche module",
        "outfitting_tab_results_title": "Résultats de la recherche",
        "outfitting_radius_label": "Module Rayon (AL)",
        "outfitting_update_db_button": "Maj DB Modules",
        "outfitting_add_to_list_btn": "Ajout module à la liste",
        "outfitting_search_list_label": "Liste des modules recherchés",
        "outfitting_remove_from_list_btn": "Enlever module de la liste",
        "outfitting_search_initial_status": "En attente d'une recherche",
        "tree_col_outfitting_station": "Station",
        "tree_col_outfitting_system": "Système",
        "tree_col_outfitting_dist_ly": "Distance AL",
        "tree_col_outfitting_pad_size": "Taille du Pad",
        "tree_col_outfitting_dist_ls": "Distance LS",
        "tree_col_outfitting_type": "Type de Station",
        "tree_col_outfitting_modules_matched_ui": "Modules recherchés",
        "status_outfitting_found_stations_multimodule": "Résultats",
        "status_outfitting_no_stations_found_multimodule": "Pas de résultats, essayez de changer votre recherche",
        "outfitting_size_filter_label": "Taille du Module",
        "outfitting_class_filter_label": "Classe du Module",
        "filter_any": "Tous",
        "outfitting_mount_filter_label": "Type de Montage",
        "mount_fixed": "Fixe",
        "mount_turreted": "Tourelle",
        "mount_gimballed": "Gimballed", # Note: Gimballed is often used in FR too for ED
        "outfitting_results_initial_status": "Résultats: statut initial",

        # --- Onglet Matériaux ---
        "materials_tab_title": "Matériaux d'Ingénierie",
        "refresh_materials_button": "🔄 Rafraîchir Matériaux",
        "material_category_raw": "Bruts",
        "material_category_manufactured": "Manufacturés",
        "material_category_encoded": "Encodés",
        "material_name_header": "Matériau",
        "material_grade_header": "Grade",
        "material_quantity_header": "Qté",
        "material_limit_header": "Limite",
        "material_percentage_header": "% Plein",
        "materials_status_idle": "Matériaux : Prêt. Appuyez sur rafraîchir pour charger l'inventaire.",
        "materials_status_not_loaded": "Matériaux : Données non chargées.",
        "materials_status_updated_at": "Matériaux mis à jour le : {timestamp}",
        "materials_status_loading": "Matériaux : Chargement de l'inventaire depuis le journal...",
        "materials_status_load_failed": "Matériaux : Échec du chargement de l'inventaire.",
        "materials_journal_dir_not_found_error": "Chargement matériaux impossible : Répertoire du journal non trouvé. Vérifiez les paramètres.",
        "materials_no_journal_events_status": "Matériaux : Aucun événement de journal trouvé. Essayez de vous connecter au jeu.",
        "materials_event_not_found_warning": "Impossible de trouver un événement 'Materials' récent dans le journal. Assurez-vous de vous être connecté au jeu récemment.",
        "materials_error_refreshing": "Erreur lors du rafraîchissement des données des matériaux : {error}",
        "materials_updated_at": "Matériels mis à jour à",
        
         # ... (vos clés françaises existantes) ...
        "multihop_trade_tab_title": "Planificateur de Routes Multi-Sauts", # Déjà ajouté

        # --- Onglet Planificateur de Routes Commerciales Multi-Sauts UI ---
        "multihop_config_frame_title": "Configuration de l'Itinéraire",
        "multihop_num_hops_label": "Nombre de Sauts (1-10) :",
        "multihop_max_ly_per_hop_label": "AL Max par Saut :",
        "multihop_start_planning_button": "▶️ Démarrer Planification",
        "multihop_restart_planning_button": "🔄 Recommencer Planification",

        "multihop_current_hop_frame_title": "Planification du Saut Actuel",
        "multihop_hop_details_label": "Saut {current_hop_num}/{total_hops_num} : Départ de {current_station_name} ({current_system_name})",
        "multihop_suggestions_label": "Top 5 Options Commerciales pour ce Saut :",
        "multihop_select_and_continue_button": "Sélectionner & Saut Suivant ({remaining_hops} restants)",
        "multihop_select_and_finish_button": "Sélectionner & Terminer Route",

        "multihop_summary_frame_title": "Récapitulatif de l'Itinéraire Planifié",
        "multihop_clear_summary_button": "Effacer Récapitulatif",

        # En-têtes de colonnes Treeview pour Multi-Hop
        "multihop_col_dest_station": "Station Destination",
        "multihop_col_dest_system": "Système",
        "multihop_col_commodity_to_buy": "Marchandise à Acheter",
        "multihop_col_profit_per_unit": "Profit/Unité",
        "multihop_col_est_total_profit": "Profit Total Est.",
        "multihop_col_distance_ly": "Dist. (AL)",
        "multihop_col_landing_pad": "Pad",
        "multihop_col_dist_to_star": "Dist. Étoile (SL)",
        "multihop_col_buy_price_at_source": "Prix Achat (Source)",
        "multihop_col_sell_price_at_dest": "Prix Vente (Dest.)",

        # Messages de Statut/Erreur pour Multi-Hop
        "multihop_status_idle": "Configurez l'itinéraire et démarrez la planification.",
        "multihop_status_input_hops_num_error": "Le nombre de sauts doit être entre 1 et 10.",
        "multihop_status_input_max_ly_error": "La distance max par saut (AL) doit être un nombre positif.",
        "multihop_status_player_info_error": "Erreur : Impossible d'obtenir le lieu/vaisseau actuel. Veuillez rafraîchir dans l'onglet Analyse.",
        "multihop_status_validating_inputs": "Multi-Sauts : Validation des entrées...",
        "multihop_status_getting_player_info": "Multi-Sauts : Récupération des données joueur initiales...",
        "multihop_status_starting_planning": "Démarrage de la planification multi-sauts...",
        "multihop_status_planning_hop": "Planification du saut {hop_num_current} sur {hop_num_total} depuis {station_name}...",
        "multihop_status_updating_market_data": "Mise à jour des données de marché pour les environs de {system_name}...",
        "multihop_status_finding_trades": "Recherche des meilleurs commerces depuis {station_name}...",
        "multihop_status_no_trades_found": "Aucun commerce profitable trouvé pour ce saut avec les critères actuels.",
        "multihop_status_select_next_hop": "Veuillez sélectionner un commerce pour le prochain saut dans la liste ci-dessus.",
        "multihop_status_route_complete": "Planification de route multi-sauts terminée. Voir le récapitulatif ci-dessous.",
        "multihop_status_route_cancelled": "Planification de route multi-sauts annulée.",
        "multihop_summary_leg": "Étape {leg_num} : De {source_station} ({source_system}) à {dest_station} ({dest_system})", # Ancienne version
        "multihop_summary_leg_with_distances": "Étape {leg_num} : De {source_station} ({source_system}) à {dest_station} ({dest_system}) [{dist_ly} AL, {dist_ls} SL]", # <<< NOUVELLE/MODIFIÉE
        "multihop_summary_buy": "  Acheter : {quantity} x {commodity_name} @ {buy_price_each:,.0f} CR l'unité.",
        "multihop_summary_sell": "  Vendre : {commodity_name} @ {sell_price_each:,.0f} CR l'unité.",
        "multihop_summary_profit_leg": "  Profit Étape : {leg_profit:,.0f} CR",
        "multihop_summary_total_profit": "Profit Total Estimé de la Route : {total_route_profit:,.0f} CR",
        
        # --- Cache Itinéraire Multi-Sauts ---
        "multihop_status_loaded_saved_route": "Dernier itinéraire sauvegardé chargé.",
        "multihop_status_no_saved_route": "Aucun itinéraire sauvegardé trouvé. Configurez un nouvel itinéraire.",
        "multihop_status_route_saved": "Itinéraire actuel sauvegardé.",
        "multihop_status_cleared_saved_route": "Itinéraire sauvegardé effacé. Configurez un nouvel itinéraire."
    }
}

CURRENT_LANG = DEFAULT_LANG

def set_language(lang_code):
    global CURRENT_LANG
    if lang_code in TRANSLATIONS:
        CURRENT_LANG = lang_code
        logger.info(f"Language set to: {lang_code}")
    else:
        CURRENT_LANG = DEFAULT_LANG
        logger.warning(f"Language code '{lang_code}' not found. Using default: {DEFAULT_LANG}")

def get_string(key, *args, **kwargs):
    try:
        base_string = TRANSLATIONS[CURRENT_LANG].get(key)
        if base_string is None: # Essayer la langue par défaut si la clé n'est pas trouvée
             base_string = TRANSLATIONS[DEFAULT_LANG].get(key)

        if base_string is None:
            logger.warning(f"Translation key '{key}' not found in '{CURRENT_LANG}' or default '{DEFAULT_LANG}'.")
            return f"<{key}>" 
        
        if args or kwargs: # Si des arguments de formatage sont passés
            return base_string.format(*args, **kwargs)
        return base_string
    except KeyError as e: # Si CURRENT_LANG ou DEFAULT_LANG n'est pas une clé valide dans TRANSLATIONS
        logger.error(f"Language code error for key '{key}': {e}. Current lang: {CURRENT_LANG}, Default: {DEFAULT_LANG}")
        return f"<{key}>!" # Fallback critique
    except Exception as e: # Autres erreurs potentielles (ex: erreur de formatage)
        logger.error(f"Error retrieving string for key '{key}' in language '{CURRENT_LANG}': {e}")
        return f"<{key}>?"


def get_available_languages():
    # Retourne les langues disponibles pour l'affichage dans les paramètres, par exemple
    return {
        "en": "English", # Code: Nom affichable
        "fr": "Français"
    }

def get_current_language_code():
    return CURRENT_LANG